### ISSUE TITLE
Restore fullscreen mode doesn't change state in localstorage

### ISSUE THREAD

**Issue by luiseduardo** [arboshiki/lobipanel#1]
When fullscreen mode, the state is saved, but when restore fullscreen mode the state in localstorage remain fullscreen.

**Comment by arboshiki** [comment]
Thanks again for submitting issue. I will find this out ASAP.

**Comment by arboshiki** [comment]
Sorry for my laaaaaaaaaaaaate response. Next time I will try to be quicker. I have fixed this bug and pushed on dev branch. It will be great if you test it.

Thank you

**Comment by luiseduardo** [comment]
Ok, no problem ;)
I wil test.
