### ISSUE TITLE
panel Drag

### ISSUE THREAD

**Issue by holmes1491** [arboshiki/lobipanel#11]
is it possible panel drag within window ???

**Comment by arboshiki** [comment]
You need to "Unpin" panel from DOM and then you can drag anywhere you want.

**Comment by holmes1491** [comment]
i mean to say  CONSTRAIN TO WINDOW and CONSTRAIN TO PARENT element

**Comment by shogunfighter** [comment]
I suggested something similar to this. But you need to modify the lobipanel.js

See >>> #12

**Comment by arboshiki** [comment]
This issue is fixed. I pushed the commit on master branch. 
Added `constrain` property.
