### ISSUE TITLE
Drag issue with Lobipanel

### ISSUE THREAD

**Issue by jqueryuser1** [arboshiki/lobipanel#12]
Anyone knows a fix for the following issue? Unpin a form then move it up in your browser until the header is not visible anymore. You won't be able to pin the window or take control of the form anymore without refreshing the entire page.

**Comment by arboshiki** [comment]
This is a bug which is going to be fixed in next updates.

**Comment by jqueryuser1** [comment]
Thank you Zura,

Any workaround to disable moving the form too high and loose control over it?

Thanks
Regards
Hichem

**Comment by arboshiki** [comment]
For now I can not think the way how it can be fixed without updating the core of the plugin.
Thank you too

**Comment by shogunfighter** [comment]
I guess you need to limit the dragging of the lobipanel inside the html document.
This tells the jquery ui (dragging module) to limit the dragging inside the html document only..
I suggest you do this.

Open the lobipanel.js > find this.enableDrag=function(){}


> this.enableDrag = function(){
>             me.$el.draggable({
>                 handle: '.panel-heading',
>                 
> > //add the following codes
> > containment: "document",
> > scroll: false
> 
> });
> return me;
> };

**Comment by jqueryuser1** [comment]
Thanks, 

 

I have tested it and it seems to only work if  the panel is unpinned when theres no scrolling on the page.

If you unpin a panel after scrolling down your page (panel located at the bottom of your page) and move it up, the issue remains.

If however you unpin a panel located at the top of the page (without scrolling down), it works.

 

Any idea ?

 

Regards

**Comment by shogunfighter** [comment]
@jqueryuser1 

I bet you just need to customize the draggable containment parameters in such a way the lobipanel wont throw out of the window/page. Maybe you can try using a different containment parameter aside from "document". You can create your own <div> and limit the dragging of the lobipanel inside that <div>

More info:
[jquery > draggable > containment](https://api.jqueryui.com/draggable/#option-containment)

**Comment by arboshiki** [comment]
This issue is fixed. I pushed the commit on master branch. 
Please check it out, if it's fixed

**Comment by jqueryuser1** [comment]
Good afternoon,

 

I was wondering whether it is possible to move the Lobipanel outside of the current page to make full use of extended or two screen monitors ?

 

Thanks

Regatds

 

Hichem

**Comment by arboshiki** [comment]
Hello,
No this is not possible not in Lobipanel and not in any other web plugin.
Browser does not allow this to move its DOM element outside of it.

On Aug 2, 2016 10:05 PM, "jqueryuser1" <notifications@github.com> wrote:

Good afternoon,



I was wondering whether it is possible to move the Lobipanel outside of the
current page to make full use of extended or two screen monitors ?



Thanks

Regatds



Hichem
