### ISSUE TITLE
Panel positions after sorting

### ISSUE THREAD

**Issue by andrius-senulis** [arboshiki/lobipanel#15]
Hi!

It's a really cool feature with being able to sort the panel by dragging. However, is there a functionality to get the positions of the panels after dragging?

Cheers,
Andrius

**Comment by arboshiki** [comment]
Hi,
This can be achieved using jquery. After panel is dragged, you need to find all `.lobipanel` elements in its parent and get index for each of them

```javascript
$('selector')
.on('dragged.lobiPanel', function(){
    var $parent = $(this).parent(),
           $children = $parent.children();
    $children.each(function(ind, el){
        console.log(el, $(el).index());
    });
})
.lobiPanel();
```

I have not tested this code. I have just written it. But it should print element and its new position in console

**Comment by andrius-senulis** [comment]
Thank you, as you suggested, I've solved it retrieving them with jQuery on the 'dragged.lobiPanel' event.

**Comment by arboshiki** [comment]
Welcome!!!
