### ISSUE TITLE
Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'

### ISSUE THREAD

**Issue by thecristen** [arboshiki/lobipanel#21]
I cannot activate this plugin - it only works on the first panel and stops.

This is the line that eventually triggers the error https://github.com/arboshiki/lobipanel/blob/master/js/lobipanel.js#L542

I have a very simple example here (see the console) http://s.codepen.io/thecristen/debug/pEZjLy

**Comment by arboshiki** [comment]
Fixed!!! Download new version from github or bower

**Comment by thecristen** [comment]
Awesome, thanks @arboshiki! :D
