### ISSUE TITLE
bower installation

### ISSUE THREAD

**Issue by swapnil0545** [arboshiki/lobipanel#24]
Hi,
When I install using "bower install lobipanel" it installs v0.3.1. Can you check why that happens?
I had to explicitly install using "bower install https://github.com/arboshiki/lobipanel.git#v0.7" . This is not really a issue but wanted to mention it.

**Comment by arboshiki** [comment]
I created new tag v0.7.1. Try to run bower install

**Comment by swapnil0545** [comment]
That fixed it I guess.
