### ISSUE TITLE
Can not drag panel to the column which has no panel from begining.

### ISSUE THREAD

**Issue by sama55** [arboshiki/lobipanel#26]
Is this the specification of jquery-UI? Do I need to add a dummy (not visible) panel?

**Comment by arboshiki** [comment]
When plugin is initialized `lobipanel-parent-sortable` class is added to parent element of panels and sortable works for only elements with `lobipanel-parent-sortable` class. 
Try to add `lobipanel-parent-sortable` class to empty div and it should work

**Comment by sama55** [comment]
Thank you for your quick reply. Only to add lobipanel-parent-sortable class had no effect. Dummy child element also seems necessary.
My code:
<div class="row">
	<div class="col-xs-12 col-sm-8 col-md-9 col-lg-9 qa-col-nopadding">
		<div class="qa-col-left lobipanel-parent-sortable">
			<div style="display:none" class="lobipanel lobipanel-sortable"></div>
			[*items_left*]
		</div>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 qa-col-nopadding">
		<div class="qa-col-right lobipanel-parent-sortable">
			<div style="display:none" class="lobipanel lobipanel-sortable"></div>
			[*items_right*]
		</div>
	</div>
</div>
Thanks.
