### ISSUE TITLE
Events are not working

### ISSUE THREAD

**Issue by haucongle** [arboshiki/lobipanel#27]
I copy all these
`$('.lobipanel').on('init.lobiPanel', function(ev, lobiPanel){
    window.console.log("init event called");
});`
`$('.lobipanel').on('beforeUnpin.lobiPanel', function(ev, lobiPanel){
    window.console.log("Before unpin", lobiPanel);
});`
`$('.lobipanel').on('onSmallSize.lobiPanel', function(ev, lobiPanel){
    window.console.log("On small size", ev, lobiPanel);
});`
`$('.lobipanel').on('loaded.lobiPanel', function(ev, lobiPanel, result, status, xhr){
    window.console.log("Loaded", ev, lobiPanel, result, status, xhr);
});`

but i don't see anything console logs

**Comment by arboshiki** [comment]
Make sure that you call this code after lobipanel is initialized. I have tested and it works.

**Comment by haucongle** [comment]
Oh sorry, I chose wrong selector.
