### ISSUE TITLE
Is there onReload / beforeReload event?

### ISSUE THREAD

**Issue by sama55** [arboshiki/lobipanel#28]
I want to refresh panel content with my Ajax process without loadUrl option. Is there event that is triggered when reload button is clicked?

**Comment by arboshiki** [comment]
Well, there is no direct callback for this. BUT, after lobipanle is initialized you can select the reload button and attach click listener to it and do whatever you want.

**Comment by sama55** [comment]
Thank you for your response. But, can I fetch event on my high level javascript? This is because, probably, I think that lobipanel will call stopPropagation() in lobipanel.js.  What do you think?

**Comment by arboshiki** [comment]
I am almost sure that you will be able to fetch event.

**Comment by sama55** [comment]
I tried to fetch event with on("click")" function of the jQuery. But, unfortunately, event did not fire. What about on your environment?

**Comment by arboshiki** [comment]
This code works fine for me
```js
$('.lobipanel').eq(0).find('[data-func=reload]').on('click', function(){
    console.log("Works!!!!");
});
```

**Comment by sama55** [comment]
I will try it. Thanks arboshiki!

**Comment by sama55** [comment]
I was able to fetch reload event. Thank you so much.
