### ISSUE TITLE
Event 'onClose.lobiPanel' is not triggered

### ISSUE THREAD

**Issue by LionelMeroni** [arboshiki/lobipanel#7]
Hello,

It seem that the 'onClose.lobiPanel' event is not triggered.

**Comment by robang10** [comment]
I am seeing the same issue with the onClose and beforeClose events.

**Comment by LionelMeroni** [comment]
Hi robang,

The beforeClose events works well for me.
There are an issue with the onClose event because the panel is removed from
the DOM. So, any event could not be triggered after that.

2016-05-16 23:12 GMT+02:00 robang10 <notifications@github.com>:

**Comment by robang10** [comment]
Yes I can get beforeClose to work.

Thanks!

**Comment by arboshiki** [comment]
`onClose` event is now triggered when animation is finished, but before panel is actually removed from DOM.
